"""add purchase_date

Revision ID: 9aa84f0ef442
Revises: fde6d94e06c7
Create Date: 2024-09-16 20:23:13.722076

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '9aa84f0ef442'
down_revision = 'fde6d94e06c7'
branch_labels = None
depends_on = None


def upgrade():
    # Add the column as nullable first
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
    
    # Set a default value for existing rows
    op.execute("UPDATE stock SET purchase_date = CURRENT_DATE WHERE purchase_date IS NULL")
    
    # Now make the column non-nullable
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('purchase_date', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('purchase_date')
    # ### end Alembic commands ###
